server:
  port: 8088

logging:
  level:
    org.springframework.*: DEBUG
    io.netty.*: DEBUG

limdongjin:
  ignasr:
    cors:
      origin: http://localhost:8080
    kafka:
      bootstrapservers: localhost:29092
      sasljaasconfig: foo
      security-protocol: PLAINTEXT
      sasl-mechanism: foo
    ignite:
      mode: local
      namespace: unused
      servicename: unused
      addresses: localhost:10800